Making the setup scripts depends on the OS
I need to dd Windows soon

diff --git a/.chezmoiscripts/run_onchange_darwin-install-packages.sh.tmpl b/.chezmoiscripts/run_onchange_darwin-install-packages.sh.tmpl
--- a/.chezmoiscripts/run_onchange_darwin-install-packages.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_darwin-install-packages.sh.tmpl
@@ -10,3 +10,24 @@ cask {{ . | quote }}
 {{ end -}}
 EOF
 {{ end -}}
+
+{{ if eq .chezmoi.os "linux" -}}
+#!/bin/bash
+
+DNF_CMD=$(which dnf)
+APT_GET_CMD=$(which apt-get)
+  
+if [[ ! -z $DNF_CMD ]]; then
+{{ range .packages.linux.dnfs -}}
+dnf install {{ . | quote }}
+{{ end -}}
+elif [[ ! -z $APT_GET_CMD ]]; then
+{{ range .packages.linux.apts -}}
+apt get {{ . | quote }}
+{{ end -}}
+ else
+    echo "error can't install package $PACKAGE"
+    exit 1;
+ fi
+EOF
+{{ end -}}
